services:
  - type: web
    name: birthday-wishes
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: SITE_PASSCODE
        sync: false
